### ISSUE TITLE
Todo list (in progress)

### ISSUE THREAD

**Issue by n1ghtie** [n1ghtie/take-home#2]
- [x] make auth (std for Laravel)
- [x] import semantic-ui scss
- [x] create new database and make proper structure based on XML
- [x] create a new artisan command to parse XML
- [x] save details and create relationship
- [x] update login/index blades with semantic-ui css classes
- [x] add and edit 401,403,404, 503 pages
- [x] index file with all the user data shown in a table
- [x] create Index controller that utilises API to pass data to index view file
- [x] create API controller and API routes
- [x] write tests for API
- [x] finish with a documentation/process of installing and using app
